### ISSUE TITLE
do u complete # Assignment 4?

### ISSUE THREAD

**Issue by johnfelipe** [tianqingztq/coursera_applied_social_network_analysis_in_python#1]

**Comment by tianqingztq** [comment]
Hi, I encountered tons of bugs on assignment 4 simply following the instructions provided in the assignment code. I finally completed that in a working-around way I would say (game the coursera rating system to get the score), and I was not satisfied with the messy coding way I did in the assignment, so I decided to not push here :). Wish you best luck

**Comment by johnfelipe** [comment]
hi dear, please share for passed is only latest for complete course:

![SNAG-0022](https://github.com/tianqingztq/coursera_applied_social_network_analysis_in_python/assets/428820/60471e33-edb2-4316-8c3d-ba6f00d35602)

send internally if u want to ingenierofelipeurrego@gmail.com
